// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtepDKmNyg6qWaQzsPwtTvO4ZnL8ocLD4',
    appId: '1:99188636945:web:b050605d673f2dd220a0b0',
    messagingSenderId: '99188636945',
    projectId: 'test-nftm',
    authDomain: 'test-nftm.firebaseapp.com',
    storageBucket: 'test-nftm.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5bRr1C2CJYj1WT7cJm45S68uN8-Nqj9c',
    appId: '1:99188636945:android:9b90e63b446da09120a0b0',
    messagingSenderId: '99188636945',
    projectId: 'test-nftm',
    storageBucket: 'test-nftm.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYqRdgnd0AE9Xl_-YIzcJivZiIA6Lh-wQ',
    appId: '1:99188636945:ios:34ecc648430949ae20a0b0',
    messagingSenderId: '99188636945',
    projectId: 'test-nftm',
    storageBucket: 'test-nftm.appspot.com',
    iosClientId: '99188636945-25efhclbuloqoe8mpjqtrr48unsmeosk.apps.googleusercontent.com',
    iosBundleId: 'com.example.nftmarket',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYqRdgnd0AE9Xl_-YIzcJivZiIA6Lh-wQ',
    appId: '1:99188636945:ios:5a448e29ac73d6e720a0b0',
    messagingSenderId: '99188636945',
    projectId: 'test-nftm',
    storageBucket: 'test-nftm.appspot.com',
    iosClientId: '99188636945-4da3sfh7122bob5hn7egh8e4vo1po7e6.apps.googleusercontent.com',
    iosBundleId: 'com.example.nftmarket.RunnerTests',
  );
}
